package com.github.misham72.communalpayments.presentation.theme

import androidx.compose.ui.graphics.Color

// Кнопки, акценты, выбранные элементы
//internal val primaryLight = Color(0xFF415F91)
val primaryLight = Color(0xFF0e6b58)
val onPrimaryLight = Color(0xFFffffff)
val primaryContainerLight = Color(0xFFcce8e2)
val onPrimaryContainerLight = Color(0xFF005141)
val secondaryLight = Color(0xFF4b635b)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFcde9de)
val onSecondaryContainerLight = Color(0xFF1A1B1E)
val tertiaryLight = Color(0xFF416277)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFc5e7ff)
val onTertiaryContainerLight = Color(0xFF002E40)
val errorLight = Color(0xFFba1a1a)
val onErrorLight = Color(0xFFffffff)
val errorContainerLight = Color(0xFFffdad6)
val onErrorContainerLight = Color(0xFF93000a)
val backgroundLight = Color(0xFFd5dbd7)
val onBackgroundLight = Color(0xFF1A1B1E)
val surfaceLight = Color(0xFFf5fbf7)
val onSurfaceLight = Color(0xFF171d1b)
val surfaceVariantLight = Color(0xFFbfc9c4)
val onSurfaceVariantLight = Color(0xFF44474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3033)
val inverseOnSurfaceLight = Color(0xFFF2F0F4)
val inversePrimaryLight = Color(0xFFAFC7F6)
val surfaceDimLight = Color(0xFFd5dbd9)
val surfaceBrightLight = Color(0xFFFAF9FD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3F7)
val surfaceContainerLight = Color(0xFFEFEDF1)
val surfaceContainerHighLight = Color(0xFFE9E7EB)
val surfaceContainerHighestLight = Color(0xFFE3E2E6)


val primaryDark = Color(0xFF86d6be)
val onPrimaryDark = Color(0xFF00382c)
val primaryContainerDark = Color(0xFF005141)
val onPrimaryContainerDark = Color(0xFFa2f2da)
val secondaryDark = Color(0xFFb2ccc2)
val onSecondaryDark = Color(0xFF1d352e)
val secondaryContainerDark = Color(0xFF344c44)
val onSecondaryContainerDark = Color(0xFFcde9de)
val tertiaryDark = Color(0xFFa9cbe3)
val onTertiaryDark = Color(0xFF0f3447)
val tertiaryContainerDark = Color(0xFF294a5e)
val onTertiaryContainerDark = Color(0xFFc5e7ff)
val errorDark = Color(0xFFffb4ab)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000a)
val onErrorContainerDark = Color(0xFFffdad6)
val backgroundDark = Color(0xFF121316)
val onBackgroundDark = Color(0xFFE3E2E6)
val surfaceDark = Color(0xFF0f1512)
val onSurfaceDark = Color(0xFFdee4e0)
val surfaceVariantDark = Color(0xFF44474E)
val onSurfaceVariantDark = Color(0xFFC4C6CF)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF44474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E6)
val inverseOnSurfaceDark = Color(0xFF2F3033)
val inversePrimaryDark = Color(0xFF475F88)
val surfaceDimDark = Color(0xFF121316)
val surfaceBrightDark = Color(0xFF38393C)
val surfaceContainerLowestDark = Color(0xFF0D0E11)
val surfaceContainerLowDark = Color(0xFF1A1B1E)
val surfaceContainerDark = Color(0xFF1F1F22)
val surfaceContainerHighDark = Color(0xFF292A2D)
val surfaceContainerHighestDark = Color(0xFF343538)

