package com.github.misham72.communalpayments.presentation.theme

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF415F91)

// internal val primaryLight = Color(0xFFD32F2F). Ярко-красный
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFD6E3FF)
internal val onPrimaryContainerLight = Color(0xFF284777)
internal val secondaryLight = Color(0xFF565F71)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFDAE2F9)
internal val onSecondaryContainerLight = Color(0xFF3E4759)
internal val tertiaryLight = Color(0xFF705575)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFFAD8FD)
internal val onTertiaryContainerLight = Color(0xFF573E5C)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF9F9FF)
internal val onBackgroundLight = Color(0xFF191C20)
internal val surfaceLight = Color(0xFFF9F9FF)
internal val onSurfaceLight = Color(0xFF191C20)
internal val surfaceVariantLight = Color(0xFFE0E2EC)
internal val onSurfaceVariantLight = Color(0xFF44474E)
internal val outlineLight = Color(0xFF74777F)
internal val outlineVariantLight = Color(0xFFC4C6D0)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2E3036)
internal val inverseOnSurfaceLight = Color(0xFFF0F0F7)
internal val inversePrimaryLight = Color(0xFFAAC7FF)
internal val surfaceDimLight = Color(0xFFD9D9E0)
internal val surfaceBrightLight = Color(0xFFF9F9FF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF3F3FA)
internal val surfaceContainerLight = Color(0xFFEDEDF4)
internal val surfaceContainerHighLight = Color(0xFFE7E8EE)
internal val surfaceContainerHighestLight = Color(0xFFE2E2E9)